### ISSUE TITLE
Remove package lock

### ISSUE THREAD

**Issue by vmikk** [SuvalineVana/pipecraft-vue#1]
Hello Martin!

During the installation, `Yarn` complains about `package-lock.json` file.
```
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn.
It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files.
To clear this warning, remove package-lock.json.
```

If there is no need in this file, could you please remove it from the version control?

With kind regards,
Vladimir

**Comment by METS0JA** [comment]
Package-lock.json has been removed.
